// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBdjNQbQSu3I7ETn5JbsC_kRS0Iui_-g',
    appId: '1:654814361692:web:f0dea0a48d7124d85b4e99',
    messagingSenderId: '654814361692',
    projectId: 'javs--vault-9a465',
    authDomain: 'javs--vault-9a465.firebaseapp.com',
    storageBucket: 'javs--vault-9a465.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwqWul1mk3jhCIS0vAg-J6_NmT77HNhk',
    appId: '1:654814361692:android:ee78a0da891563805b4e99',
    messagingSenderId: '654814361692',
    projectId: 'javs--vault-9a465',
    storageBucket: 'javs--vault-9a465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiSSg7sTkAGScxaPAwaaS1Eld_fSnSLWU',
    appId: '1:654814361692:ios:b7a871bc831081c15b4e99',
    messagingSenderId: '654814361692',
    projectId: 'javs--vault-9a465',
    storageBucket: 'javs--vault-9a465.firebasestorage.app',
    iosBundleId: 'com.javs.secureMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiSSg7sTkAGScxaPAwaaS1Eld_fSnSLWU',
    appId: '1:654814361692:ios:b7a871bc831081c15b4e99',
    messagingSenderId: '654814361692',
    projectId: 'javs--vault-9a465',
    storageBucket: 'javs--vault-9a465.firebasestorage.app',
    iosBundleId: 'com.javs.secureMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrBdjNQbQSu3I7ETn5JbsC_kRS0Iui_-g',
    appId: '1:654814361692:web:06030e63b3c03a2f5b4e99',
    messagingSenderId: '654814361692',
    projectId: 'javs--vault-9a465',
    authDomain: 'javs--vault-9a465.firebaseapp.com',
    storageBucket: 'javs--vault-9a465.firebasestorage.app',
  );
}
